server:
  port: 8000

# Spring Boot Admin Serveré…ç½®
spring:
  boot:
    admin:
      monitor:
        status-lifetime: 100000
      ui:
        external-views:
          - label: "ğŸš€"
            url: https://springboot.plus
            order: 2000

# Spring Boot Admin ç™»å½•è´¦å·å¯†ç 
xiu-core:
  admin:
    username: admin
    password: 123456